### ISSUE TITLE
I2C Connectors

### ISSUE THREAD

**Issue by JohnP2137** [TDStrasser/KookaBlockly-Reference#10]
In all of the I2C connected sensors you say that any of the K's connectors (P1-5) can also be used. But only P3 can accommodate the 4-pin plug I have always assumed was used for 2IC connections. What am I missing?

**Comment by TDStrasser** [comment]
P3 contains 2 GPIO pins.  Any of the Pins on the Kookaberry can be used for I2C communications but would require a different physical arrangement to make the plugs and sockets work.
KookaBlockly can now be used with expander boards via the edge connector, and also with the bare Pico processor where all the GPIOs are exposed by using DuPont push-on connectors. Leads that are supplied with the Gravity I2C boards have DuPont connectors at one end and 4-pin JST connectors on the other.
The ability to specify GPIO using a text string has also been provided. Just unplug the drop-down plug list block and plug in a string block to the input.  The Pico's GPIO specification is just a number (eg. "16") and the firmware also accepts "GP16".  This has been the subject of much debate leading up to the last firmware release and is reflected in KookaBlockly.

No need for any action on the manual.  It isn't a hardware manual.

**Comment by JohnP2137** [comment]
👍 Tks
Cheers,
John Phillips
Mob: 0419 830 851
