### ISSUE TITLE
Actuators

### ISSUE THREAD

**Issue by JohnP2137** [TDStrasser/KookaBlockly-Reference#11]
Given that one of the better Tutorials/apps on the website ([Bushfire Risk Indicator)](https://learn.auststem.com.au/learning-plan/bushfire-risk-indicator/) uses a small Hobby servo plugged directly into a K,  "may be possible" in the 7th para/sentence of your intro might be changed to "is possible" with a reference to the Tutorial - which takes a student through the whole gamut of servo operation in an experiential fashion.

Also, servos also operate using PWM - just not in quite the same way as when used to drive a motor at varying speeds. Your text gives the impression that only motors use PWM. The [MicroServo peripheral](https://learn.auststem.com.au/peripheral/micro-servo/) description on the website (which you reference at the end of the section, explains the use of PWM for servo control (when the provided references are also accessed) very well I think.

**Comment by TDStrasser** [comment]
First point amended as suggested. Yes it is possible but not recommended to drive a servo directly.

Second item I removed the paragraph referencing motors and PWM. It confuses rather than clarifies and as speed control of motors is handled under Pins, there is no need to add complexity here.
