### ISSUE TITLE
Loops

### ISSUE THREAD

**Issue by JohnP2137** [TDStrasser/KookaBlockly-Reference#13]
Would it be useful to state that the simple value block to count the number of iterations can be found in the Maths category? When I started out with KB, I didn't know where to find this most popular block.

Maybe give an example for why the third loop is particularly useful? Programmers will know this but beginners might scratch their heads at its apparent complexity.

**Comment by TDStrasser** [comment]
Cross references to the Maths and Variables categories added with suitable text.

By third, I assume you mean the "for i from to by" loop block.
I have put in a simple example of counting by 3.
