### ISSUE TITLE
Change Variable

### ISSUE THREAD

**Issue by JohnP2137** [TDStrasser/KookaBlockly-Reference#14]
Could you provide an example of why you would want this block? Obviously it is important enough to have its own block but I  have not done enough programming to appreciate its utility.

**Comment by TDStrasser** [comment]
I have included an example that counts button presses on the Kookaberry and displays the running totals for B, C and D. Button A exits as usual.
Variables are set up to totalise presses for each of the buttons. When a button was_pressed the variable change block adds 1 to the number in the respective variable.

**Comment by JohnP2137** [comment]
👍 Tks for the explanation.
Cheers,
John Phillips
Mob: 0419 830 851
