### ISSUE TITLE
KookaBlockly docs

### ISSUE THREAD

**Issue by JulianDinsdale** [TDStrasser/KookaBlockly-Reference#15]
Copyright info at Botton of Read the Docs pages to read

The KookaBlockly Documentation is Copyright () 2019 - 2024 AustSTEM Foundation and contributors.  Last updated on 3 Jan 2024

**Comment by TDStrasser** [comment]
Noted. I now think I know how this work insofar as last update is concerned. I'll try some experiments and close if successful.

**Comment by TDStrasser** [comment]
This now works:
<img width="547" alt="image" src="https://github.com/TDStrasser/KookaBlockly-Reference/assets/43877585/1d90fe33-6601-478e-babb-9ae4cd419fe6">
