### ISSUE TITLE
Documentation - Two parts

### ISSUE THREAD

**Issue by JulianDinsdale** [TDStrasser/KookaBlockly-Reference#16]
The introduction states the document is in Two parts this should be clearer in the docs
Part 1. Working with KookaBlockly ( text in bold)
Part 2. KookaBlockly Reference Document (text in bold) a reference document for the visual functional blocks in KookaBlockly

**Comment by TDStrasser** [comment]
I have attempted a restructure into parts 1 (Working) and part 2 (Blocks Reference) and will see if it works as I intended.
The issue I have is working out how to do a trial without disturbing the /latest published versions.

**Comment by TDStrasser** [comment]
I have created a "testing" branch on GitHub and will manage releases from that to "main" which publishes as "latest".
To view the testing branch, go to this URL: https://kookablockly-reference-guide.readthedocs.io/en/testing/index.html
