### ISSUE TITLE
KookaBlockly Docs - Contents

### ISSUE THREAD

**Issue by JulianDinsdale** [TDStrasser/KookaBlockly-Reference#17]
In the “Contents” need to show the two parts more clearly
ie Part 1 being Working with KookaBlockly and
Part 2  KookaBlockly Reference Document

noted that when creating a pdf document the format is quite different and can be confusing

**Comment by TDStrasser** [comment]
See issue 16 - I have restructured.  Yet to work out how to tame the PDF bit - will do that later.
