### ISSUE TITLE
KookaBlockly category access

### ISSUE THREAD

**Issue by JulianDinsdale** [TDStrasser/KookaBlockly-Reference#18]
When using the Contents to access a Category we should have the same look and feel.  Should see the Category selected on the left and the associated blocks on the right.
The Control category is a good example.
When some categories are selected the blocks are further down the text and some do not have both the category and blocks shown

**Comment by TDStrasser** [comment]
All palette images retaken to show the category bar on the left.  Involved some width reformatting and taking into account maximum height to fit into a page in the PDF version. Some figures had page overruns in the PDF.
Now working on figure numbering and referencing as the PDF moves large figures to the next page away from the text.
