### ISSUE TITLE
KookaBlockly - Virtual Display

### ISSUE THREAD

**Issue by JulianDinsdale** [TDStrasser/KookaBlockly-Reference#19]
Need to adopt the concept of the Kookaberry - Virtual Display
Need to elaborate in Part  the reason and features of the Virtual Display
Need to describe that the functions on the Virtual Display are
a) the “Kookaberry Reset” button replicates the hardware Reset button the Kookaberry
b) the “Kookaberry menu” button replaces the “hold down button B and press and release Reset”
c) the three LEDs replicate the three hardware LEDs on the Kookaberry
d) the four buttons replicate those on the KookaBerry

**Comment by TDStrasser** [comment]
OK, made an attempt within the note under Inspection Buttons / Show display.
