### ISSUE TITLE
Functional Block Reference: External Clock

### ISSUE THREAD

**Issue by JohnP2137** [TDStrasser/KookaBlockly-Reference#2]
Get External Clock - Simple Time.  Spelling mistake 3rd para first SCK should be SCL

**Comment by JohnP2137** [comment]
Same issue in all External Clock block descriptions

**Comment by JohnP2137** [comment]
...and also in the Clock Introduction (para 5)

**Comment by TDStrasser** [comment]
At least I was consistent! All remedied for next iteration.
