### ISSUE TITLE
Inspection Buttons

### ISSUE THREAD

**Issue by JulianDinsdale** [TDStrasser/KookaBlockly-Reference#21]
Inspection Buttons - Show Display

suggest. ………this button will open the Kookaberry Virtual Display………
The Virtual Display will mirror the……….on the Kookaberry

**Comment by TDStrasser** [comment]
I think ..Kookaberry shown in virtual form" is more accurate (ie. not just the display).
The note underneath now elaborates per your previously raised issue.
Look at the next publication of the testing version and raise another issue if still not satisfied.
