### ISSUE TITLE
KookaBlockly - Inspection Buttons

### ISSUE THREAD

**Issue by JulianDinsdale** [TDStrasser/KookaBlockly-Reference#22]
Inspection Buttons - Show Display
Rename Kookaberry Display to Kookaberry Virtual Display

in the Note below add RP2040
Ie.  …….load Kookaberry RP2040 firmware onto ………

**Comment by TDStrasser** [comment]
?? The figure is titled: Virtual Kookaberry window
Kookaberry display is the title bar within the KookaTW software, a screen grab of which is shown.
