### ISSUE TITLE
KookaBlockly Contents

### ISSUE THREAD

**Issue by JulianDinsdale** [TDStrasser/KookaBlockly-Reference#23]
In the Contents
Rename “KookaBlockly Function Blocks Reference” to “KookaBlockly Reference Document” see previous issues

**Comment by TDStrasser** [comment]
Don't quite agree. 
Part 2 is a reference for what functions the blocks provide, hence the name.
The whole documents, Parts 1 and 2, is the KookaBlockly Reference Guide (aka document).
