### ISSUE TITLE
Button  Category 

### ISSUE THREAD

**Issue by JulianDinsdale** [TDStrasser/KookaBlockly-Reference#25]
Buttons - Kookaberry display
Rename “ Virtual Kookaberry “ to “Kookaberry Virtual Display” 

also in text change

Button functions……….on the Kookaberry Virtual Display which is ………..

**Comment by TDStrasser** [comment]
Maybe I'm too pedantic.
The figure is that of the Virtual Kookaberry (the whole Kookaberry user interface), not a Kookaberry Virtual Display (it has buttons too)
