### ISSUE TITLE
KookaBlockly - Sensors

### ISSUE THREAD

**Issue by JulianDinsdale** [TDStrasser/KookaBlockly-Reference#29]
Sensors - External Sensors- DS18x20
The manufacturer of the temp sensing DS18x20 chip requires a 4K7 resistor pull up resistor to make the chip work correctly.  With some microcontrollers the internal pull up resistor may work on some DS18x20 chips but not all of them.

**Comment by TDStrasser** [comment]
Added a note:
The manufacturer of the temperature sensing DS18x20 chip requires a 4700 ohm (often referred to as a 4K7) pull-up resistor  to make the chip work correctly. The **Kookaberry**'s and **Pi Pico**'s internal pull up resistor may work on some DS18x20 chips but not all of them. Try a different make of DS18x20 sensor if troublesome operation occurs.
