### ISSUE TITLE
KookaBlockly - Radio

### ISSUE THREAD

**Issue by JulianDinsdale** [TDStrasser/KookaBlockly-Reference#32]
Radio Category 

1) MoveRadio Blocks palette to top
2) The internal Radio is implemented as a “packet radio” only and is compatible with the Micro- Bit packet radio
3) The size of the radio blocks are not consistent and could be a little smaller

**Comment by TDStrasser** [comment]
Remedied and not on the Micro:Bit added here and in the glossary.
