### ISSUE TITLE
Display

### ISSUE THREAD

**Issue by JohnP2137** [TDStrasser/KookaBlockly-Reference#6]
I know it is obvious to you, but it certainly wasn't to me when I started this.... You might reference your description of the "display set font..."  block but an explanation like this right up front could be useful " a text symbol is made up of a matrix of pixels, and that font size (eg mono8x8) is actually a matrix of 8 pixels wide and 8 pixels high."

**Comment by TDStrasser** [comment]
A text font isn't only 8x8.  It is a matrix as given by the font size, i.e. 5x5, 6x7, 8x13, 12x12, 8x8 etc.
The default font is 8x8.
This is already explained in the Set Font block description.
No action needed.
