### ISSUE TITLE
Display Show

### ISSUE THREAD

**Issue by JohnP2137** [TDStrasser/KookaBlockly-Reference#7]
I do not understand the purpose of the second sentence. (Maybe because I am not a natural programmer...) The Show Script box indicates two kooka.display.show () bits of script???

**Comment by TDStrasser** [comment]
I have clarified the language.
It should have said that a display.show() will be generated at the end of any script using the display blocks.
This means that the physical display will only be refreshed at the end of the script.
If the display needs to be "live", then a display.show() will be needed at earlier junctures in the script, for example at the end of every loop that updates the display.
