### ISSUE TITLE
Pin-PWM

### ISSUE THREAD

**Issue by JohnP2137** [TDStrasser/KookaBlockly-Reference#8]
You might also mention that PWM is used for servo control. See also my expansion on this topic under Issue Actuators

**Comment by TDStrasser** [comment]
Why?  It will just confuse people.  I removed the motors reference from Actuators.
KookaBlockly is for beginning users.  What use will they make of such information?
Yes, it might be possible they mimic the Servo blocks using duty cycle PWM control, but that's for more advanced users.
If they read up on servos and motors they may be able to join the dots themselves.
I'll leave this issue open for further discussion if needed.
For the moment I see no need for a change to the KookaBlockly Guide.

**Comment by TDStrasser** [comment]
As no more comments, issue closed.
